### ISSUE TITLE
Not able to edit profile

### ISSUE THREAD

**Issue by Arav-Agarwal** [ksjdragon/hourglass#80]
![jdjdjd](https://cloud.githubusercontent.com/assets/10763018/18156247/e3a7b016-6fe2-11e6-8dd9-ada291434fef.PNG)

**Comment by Arav-Agarwal** [comment]
Can't change preferences until you have personal information

**Comment by yamanq** [comment]
I don't know how you are using the function, but the cause is likely a client side issue: If you edit the grade field, and your school is undefined, client sends an undefined school, which is not acceptable and vice versa. The fix is changing school and grade, then other preferences. Another fix is relaxing the security on server
