### ISSUE TITLE
Client cleanup

### ISSUE THREAD

**Issue by ksjdragon** [ksjdragon/hourglass#87]
Please list off small bugs and issues in a checklist

**Comment by yamanq** [comment]
- [ ] not aligned and not enough contrast on tip
![image](https://cloud.githubusercontent.com/assets/8166212/18366596/55373492-75e5-11e6-9e51-f9f76123fe7e.png)
- [ ] Not noticeable
![image](https://cloud.githubusercontent.com/assets/8166212/18366734/e338cc42-75e5-11e6-9001-1031f0ccfd41.png)
- [ ] When on calendar mode and I press on a day to create a work, the sidebar opens. A second later, it goes to my default, classes mode, instead of staying on calendar mode

**Comment by ksjdragon** [comment]
- [ ] 
![screenshot from 2016-09-09 02 25 23](https://cloud.githubusercontent.com/assets/8921294/18377369/b7b7d1d6-7634-11e6-8157-b4fedc162b01.png)

**Comment by ksjdragon** [comment]
Can't reproduce problem 3

**Comment by yamanq** [comment]
1. set default mode to classes
2. go to calendar mode
3. press on a date
4. the sidebar should stay open with a "pick a class" but goes to classes mode

**Comment by ksjdragon** [comment]
- [ ] 
![screenshot from 2016-09-09 08 27 33](https://cloud.githubusercontent.com/assets/8921294/18386842/55b83880-7667-11e6-9853-1bec7c9b218d.png)

**Comment by ksjdragon** [comment]
- [ ] Align filter selected Icon
- [ ] Hovering on calendar doesn't work

**Comment by ksjdragon** [comment]
Open this issue if any more appear.
